YARN-11931. Fix router webapp tests by adding EclipseLink test dependency. (#8261) Contributed by Shilun Fan.
* YARN-11931. Fix router webapp tests by adding EclipseLink test dependency.

After upgrading to Jersey 2.46, TestRouterWebServicesREST and
TestFederationWebApp fail with NoClassDefFoundError for
org.eclipse.persistence.internal.queries.ContainerPolicy.

This patch adds org.eclipse.persistence:org.eclipse.persistence.core
as a test dependency in hadoop-yarn-server-router/pom.xml.

Additionally, fixed a classpath concatenation bug in JavaProcess.java
where File.pathSeparator was missing when appending test resources path.

Test Results:
- TestRouterWebServicesREST: 42 tests passed
- TestFederationWebApp: 52 tests passed

Reviewed-by: Chris Nauroth <cnauroth@apache.org>
Signed-off-by: Shilun Fan <slfan1989@apache.org>
(cherry picked from commit b6063575582e0ff8892e051d74b4d34eeb243ade)